import {
  AssistantAction,
  CommandDangerLevel,
  SecurityConfirmationRequest,
} from '../types';
import { androidDeviceManager } from './androidDeviceManager';

export interface ConfirmationDecision {
  confirmed: boolean;
  requestId: string;
  action: AssistantAction;
  userComment?: string;
}

/**
 * SecurityConfirmationManager
 * Enforces strict user confirmation for high-risk, destructive, or sensitive operations.
 * Protects against accidental execution of destructive CLI commands, file deletions,
 * or sensitive system modifications generated by AI models.
 */
export class SecurityConfirmationManager {
  private static instance: SecurityConfirmationManager;
  private pendingRequest: SecurityConfirmationRequest | null = null;
  private listeners: Array<(req: SecurityConfirmationRequest | null) => void> = [];
  private pendingResolvers: Map<string, (decision: boolean) => void> = new Map();

  private constructor() {}

  public static getInstance(): SecurityConfirmationManager {
    if (!SecurityConfirmationManager.instance) {
      SecurityConfirmationManager.instance = new SecurityConfirmationManager();
    }
    return SecurityConfirmationManager.instance;
  }

  /**
   * Evaluates whether an action requires explicit confirmation
   */
  public evaluateRequiresConfirmation(action: AssistantAction): {
    requiresConfirmation: boolean;
    riskLevel: 'LOW' | 'MEDIUM' | 'HIGH';
    isDestructive: boolean;
    explanation: string;
    explanationBn: string;
  } {
    // 1. Termux Command Analysis
    if (action.type === 'termux_run' && action.payload?.command) {
      const safety = androidDeviceManager.evaluateCommandSafety(action.payload.command);
      if (safety.dangerLevel === 'destructive') {
        return {
          requiresConfirmation: true,
          riskLevel: 'HIGH',
          isDestructive: true,
          explanation: `Destructive Terminal Command: "${action.payload.command}". ${safety.explanation}`,
          explanationBn: `ধ্বংসাত্মক টার্মিনাল কমান্ড: "${action.payload.command}"। এটি ডিভাইসের ডেটা মুছে ফেলতে বা সিস্টেমে বড় পরিবর্তন করতে পারে।`,
        };
      }
      if (safety.dangerLevel === 'privileged' || safety.requiresConfirmation) {
        return {
          requiresConfirmation: true,
          riskLevel: 'MEDIUM',
          isDestructive: false,
          explanation: `Privileged/Sensitive Terminal Command: "${action.payload.command}".`,
          explanationBn: `প্রিভিলেজড টার্মিনাল কমান্ড: "${action.payload.command}"। চালানোর আগে আপনার অনুমোদন প্রয়োজন।`,
        };
      }
    }

    // 2. File Deletion & Management
    if (action.type === 'read_files' && (action.payload?.path?.includes('delete') || (action.payload as any)?.deleteFile)) {
      return {
        requiresConfirmation: true,
        riskLevel: 'HIGH',
        isDestructive: true,
        explanation: `Permanent File Deletion: Attempting to delete file "${action.payload.path || 'selected files'}". This cannot be undone.`,
        explanationBn: `ফাইল স্থায়ীভাবে মুছে ফেলার নির্দেশ: "${action.payload.path || 'নির্বাচিত ফাইল'}" মুছে ফেলা হবে। এটি ফেরত আনা সম্ভব নয়।`,
      };
    }

    // 3. Sensitive Phone Calls or Direct Messaging
    if (action.type === 'phone_call' && action.payload?.phone) {
      return {
        requiresConfirmation: true,
        riskLevel: 'MEDIUM',
        isDestructive: false,
        explanation: `Initiate Direct Phone Call to ${action.payload.contactName || action.payload.phone}.`,
        explanationBn: `${action.payload.contactName || action.payload.phone} নম্বরে সরাসরি ফোন কল ডায়াল করা হবে।`,
      };
    }

    // 4. Explicit Flag set by AI or Rules
    if (action.requiresExplicitConsent) {
      return {
        requiresConfirmation: true,
        riskLevel: 'HIGH',
        isDestructive: false,
        explanation: `Explicit User Authorization Required for: ${action.title}.`,
        explanationBn: `${action.titleBn || action.title} সম্পাদন করার জন্য আপনার স্পষ্ট অনুমতি প্রয়োজন।`,
      };
    }

    return {
      requiresConfirmation: false,
      riskLevel: 'LOW',
      isDestructive: false,
      explanation: 'Safe read-only or standard interaction.',
      explanationBn: 'নিরাপদ অপারেশন।',
    };
  }

  /**
   * Request confirmation from the user (returns Promise resolving to boolean)
   */
  public requestConfirmation(action: AssistantAction): Promise<boolean> {
    const evalResult = this.evaluateRequiresConfirmation(action);
    const reqId = `conf_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`;

    const request: SecurityConfirmationRequest = {
      id: reqId,
      action,
      riskLevel: evalResult.riskLevel,
      title: action.title,
      titleBn: action.titleBn || action.title,
      explanation: evalResult.explanation,
      explanationBn: evalResult.explanationBn,
      command: action.payload?.command,
      targetApp: action.targetApp,
      packageName: action.packageName,
      payloadSummary: JSON.stringify(action.payload || {}),
      timestamp: Date.now(),
      isDestructive: evalResult.isDestructive,
    };

    this.pendingRequest = request;
    this.notifyListeners();

    return new Promise<boolean>((resolve) => {
      this.pendingResolvers.set(reqId, resolve);

      // Auto-timeout after 60 seconds (reject by default for safety)
      setTimeout(() => {
        if (this.pendingResolvers.has(reqId)) {
          this.resolveRequest(reqId, false, 'Confirmation timed out');
        }
      }, 60000);
    });
  }

  /**
   * Resolve pending request (user clicked Approve or Deny)
   */
  public resolveRequest(requestId: string, confirmed: boolean, reason?: string) {
    if (this.pendingRequest && this.pendingRequest.id === requestId) {
      const resolver = this.pendingResolvers.get(requestId);
      if (resolver) {
        resolver(confirmed);
        this.pendingResolvers.delete(requestId);
      }

      androidDeviceManager.addAuditLog({
        actionTitle: `Security Confirmation: ${this.pendingRequest.title}`,
        status: confirmed ? 'allowed' : 'denied',
        details: `User ${confirmed ? 'APPROVED' : 'DENIED'} action: ${this.pendingRequest.explanation}${reason ? ` (${reason})` : ''}`,
      });

      this.pendingRequest = null;
      this.notifyListeners();
    }
  }

  public getPendingRequest(): SecurityConfirmationRequest | null {
    return this.pendingRequest;
  }

  public onRequest(listener: (req: SecurityConfirmationRequest | null) => void): () => void {
    return this.subscribe(listener);
  }

  public subscribe(listener: (req: SecurityConfirmationRequest | null) => void): () => void {
    this.listeners.push(listener);
    listener(this.pendingRequest);
    return () => {
      this.listeners = this.listeners.filter((l) => l !== listener);
    };
  }

  public addListener(listener: (req: SecurityConfirmationRequest | null) => void): () => void {
    return this.subscribe(listener);
  }

  private notifyListeners() {
    this.listeners.forEach((l) => {
      try {
        l(this.pendingRequest);
      } catch (e) {
        console.error('[SecurityConfirmation] Listener error:', e);
      }
    });
  }
}

export const securityConfirmationManager = SecurityConfirmationManager.getInstance();
